// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/a-propos" | "/admin/dashboard" | "/admin/login" | "/admin/modules/albums" | "/admin/modules/avant-apres" | "/admin/modules/blog" | "/admin/modules/blog-categories" | "/admin/modules/carte-canada" | "/admin/modules/comptes" | "/admin/modules/demandes" | "/admin/modules/devis" | "/admin/modules/faq" | "/admin/modules/galerie" | "/admin/modules/gallery-categories" | "/admin/modules/messages" | "/admin/modules/parametres" | "/admin/modules/recrutement" | "/admin/modules/rendez-vous" | "/admin/modules/services" | "/admin/modules/temoignages" | "/admin/modules/transactions" | "/admin/notifications" | "/avant-apres" | "/blog" | "/blog/[slug]" | "/blog/article" | "/conditions-utilisation" | "/contact" | "/devis" | "/faq" | "/galerie" | "/mentions-legales" | "/paiement" | "/politique-confidentialite" | "/recrutement" | "/rendez-vous" | "/services" | "/services/[slug]" | "/services/detail" | "/temoignages"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/a-propos": {}
  "/admin/dashboard": {}
  "/admin/login": {}
  "/admin/modules/albums": {}
  "/admin/modules/avant-apres": {}
  "/admin/modules/blog": {}
  "/admin/modules/blog-categories": {}
  "/admin/modules/carte-canada": {}
  "/admin/modules/comptes": {}
  "/admin/modules/demandes": {}
  "/admin/modules/devis": {}
  "/admin/modules/faq": {}
  "/admin/modules/galerie": {}
  "/admin/modules/gallery-categories": {}
  "/admin/modules/messages": {}
  "/admin/modules/parametres": {}
  "/admin/modules/recrutement": {}
  "/admin/modules/rendez-vous": {}
  "/admin/modules/services": {}
  "/admin/modules/temoignages": {}
  "/admin/modules/transactions": {}
  "/admin/notifications": {}
  "/avant-apres": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/blog/article": {}
  "/conditions-utilisation": {}
  "/contact": {}
  "/devis": {}
  "/faq": {}
  "/galerie": {}
  "/mentions-legales": {}
  "/paiement": {}
  "/politique-confidentialite": {}
  "/recrutement": {}
  "/rendez-vous": {}
  "/services": {}
  "/services/[slug]": { "slug": string; }
  "/services/detail": {}
  "/temoignages": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
