// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/a-propos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/a-propos">> = Specific
  const handler = {} as typeof import("../../app/a-propos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/albums/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/albums">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/albums/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/avant-apres/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/avant-apres">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/avant-apres/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/blog-categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/blog-categories">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/blog-categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/blog">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/carte-canada/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/carte-canada">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/carte-canada/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/comptes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/comptes">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/comptes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/demandes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/demandes">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/demandes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/devis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/devis">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/devis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/faq">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/galerie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/galerie">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/galerie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/gallery-categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/gallery-categories">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/gallery-categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/messages">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/parametres/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/parametres">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/parametres/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/recrutement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/recrutement">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/recrutement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/rendez-vous/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/rendez-vous">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/rendez-vous/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/services">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/temoignages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/temoignages">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/temoignages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/modules/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modules/transactions">> = Specific
  const handler = {} as typeof import("../../app/admin/modules/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/notifications">> = Specific
  const handler = {} as typeof import("../../app/admin/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/avant-apres/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/avant-apres">> = Specific
  const handler = {} as typeof import("../../app/avant-apres/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/article/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/article">> = Specific
  const handler = {} as typeof import("../../app/blog/article/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/conditions-utilisation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/conditions-utilisation">> = Specific
  const handler = {} as typeof import("../../app/conditions-utilisation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/devis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devis">> = Specific
  const handler = {} as typeof import("../../app/devis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/galerie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galerie">> = Specific
  const handler = {} as typeof import("../../app/galerie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mentions-legales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mentions-legales">> = Specific
  const handler = {} as typeof import("../../app/mentions-legales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/paiement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/paiement">> = Specific
  const handler = {} as typeof import("../../app/paiement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/politique-confidentialite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/politique-confidentialite">> = Specific
  const handler = {} as typeof import("../../app/politique-confidentialite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recrutement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recrutement">> = Specific
  const handler = {} as typeof import("../../app/recrutement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rendez-vous/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rendez-vous">> = Specific
  const handler = {} as typeof import("../../app/rendez-vous/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/services/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/[slug]">> = Specific
  const handler = {} as typeof import("../../app/services/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/services/detail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/detail">> = Specific
  const handler = {} as typeof import("../../app/services/detail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/temoignages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/temoignages">> = Specific
  const handler = {} as typeof import("../../app/temoignages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
